name: gee-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python>=3.9,<3.12
  
  # Core Earth Engine and Geospatial
  - earthengine-api>=0.1.384
  - geemap>=0.29.0
  - folium>=0.14.0
  - geopandas>=0.14.0
  - rasterio>=1.3.0
  - pyproj>=3.4.0
  - proj>=9.0.0
  - gdal>=3.7.0
  
  # Interactive Mapping and Visualization
  - ipywidgets>=8.0.0
  - ipyleaflet>=0.17.0
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - notebook>=7.0.0
  
  # Dashboard Frameworks
  - streamlit>=1.28.0
  - voila>=0.5.0
  
  # Data Analysis and Visualization
  - pandas>=2.0.0
  - numpy>=1.24.0
  - xarray>=2023.8.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  - altair>=5.0.0
  
  # Scientific Computing
  - scipy>=1.11.0
  - scikit-learn>=1.3.0
  - dask>=2023.8.0
  
  # Utility Libraries
  - requests>=2.31.0
  - python-dotenv>=1.0.0
  - psutil>=5.9.0
  - click>=8.1.0
  
  # Development and Testing
  - pytest>=7.4.0
  - black>=23.7.0
  - flake8>=6.0.0
  - mypy>=1.5.0
  
  # Authentication and Cloud Services
  - google-auth>=2.22.0
  
  # Additional packages via pip
  - pip
  - pip:
    - pydeck>=0.8.0
    - google-cloud-storage>=2.10.0
    - streamlit-folium>=0.15.0
    - geemap[extra]>=0.29.0

# Environment variables to set
variables:
  PROJ_DATA: $CONDA_PREFIX/share/proj
  PROJ_LIB: $CONDA_PREFIX/share/proj
  GDAL_DATA: $CONDA_PREFIX/share/gdal